### ISSUE TITLE
The Calendar Popup needs an "OK" button 

### ISSUE THREAD

**Issue by marcoherbst** [evercam/ex_nvr#258]
From this view:
![image](https://github.com/evercam/ex_nvr/assets/5648894/feeebd59-ab6e-4d73-a63b-959cb48511ca)

I don't know how to accept the chosen date/time.

Spotted by Waqas

**Comment by gBillal** [comment]
This is the default calendar and we don't have a way to update it. Just select the date a click away and it'll be set (don't click outside the modal)

**Comment by marcoherbst** [comment]
Could I get a second opinion on this? It feels wrong. 
I'd like to reopen this and tag @KamelBadji  
If this really is the normal way for a calendar to behave then I'm happy for Kamel to close it.

**Comment by gBillal** [comment]
A button is unnecessary in this component because you have many ways of updating the calendar.

- You can type directly in the component without even opening the dialog (and use left/right keyboard keys to navigate)
- Click on enter will close the dialog also
- Click on the calendar button when you finish selecting a date and it'll also close

**Comment by marcoherbst** [comment]
I have learned not to debate longer than 3 replies with Billal. Closing :)
