### ISSUE TITLE
BIF: Inconsistent aspect ratio between BIF thumbnails and the HLS stream

### ISSUE THREAD

**Issue by halimb** [evercam/ex_nvr#337]
### Description

After the changes introduced by https://github.com/evercam/ex_nvr/pull/314 , BIF thumbnails have a different aspect in comparison with the HLS stream.

### Example
| Before [v0.8.0](https://github.com/evercam/ex_nvr/releases/tag/v0.8.0)| After [v0.8.0](https://github.com/evercam/ex_nvr/releases/tag/v0.8.0)|
| ------ | ----- |
|![before](https://github.com/evercam/ex_nvr/assets/20999471/21133a8b-41eb-42a5-a0ec-190b503e857b)| ![after](https://github.com/evercam/ex_nvr/assets/20999471/963037a2-ca06-455d-af06-061e9149febb) |

### Desired outcome
Conserve the same aspect ratio as the main stream.

**Comment by jakew009** [comment]
It's because the bif files are generated from the sub stream but the recording must be playing the main stream.

<img width="480" alt="image" src="https://github.com/evercam/ex_nvr/assets/3781208/8a73c490-3a8e-43f3-ac73-90b8a33f6213">

<img width="558" alt="image" src="https://github.com/evercam/ex_nvr/assets/3781208/60fbc3e5-2e1c-4fe5-a616-32a67afadae1">

If the sub stream was changed to 640x360 the problem would go away

<img width="270" alt="image" src="https://github.com/evercam/ex_nvr/assets/3781208/ca2d5842-cf7e-4aa2-9be6-5bb9fa5ec154">

**Comment by marcoherbst** [comment]
@halimb as Jake says, I dont think this is a big or an issue, it's just the way things are. 
@FerielKHA you might explain this in the wiki in case the question raises its head again and then close this issue.

**Comment by halimb** [comment]
ok, in the meantime, I'll force the aspect ratio in the frontend to be the same as the main stream (different FoV, but not noticeable for the usecase)

**Comment by marcoherbst** [comment]
I dont think this is an issue for the software to fix. In Evercam we will solve this by forcing the bif to be the same aspect ratio as the stream playing. In ExNVR we dont use the bif, so it's not a subject. Billal, reopen if you disagree.
